#include <iostream>
#include "linkedList.h"
#include "treeNode.h"
#include "HashTable.h"
#include "sumTo.h"
#include "digitalRoot.h"
#include <aieLog.h>
#include <aieException.h>
#include <Windows.h>
#include <string>

std::string g_exeFolder;

/*******************************************************************************
This function returns the full path to the folder that contains the current
executable. Note that there is NO trailing backslash.
********************************************************************************/
std::string getExecutableFolder()
{
    char buffer[MAX_PATH];
    GetModuleFileName(NULL, buffer, MAX_PATH);
    char *pos;
    if (pos = strrchr(buffer, '\\'))
    {
        *pos = 0;
    }

    return buffer;
}

int letterToNumber(char letter)
{
    if (letter >= 'a' && letter <= 'z')
    {
        return (int)(letter - 'a' + 1);
    }
    else if (letter >= 'A' && letter <= 'Z')
    {
        return (int)(letter - 'A' + 1);
    }
    else
    {
        return 0;
    }
}

template<typename dataType>
// returns true if input is even
bool isEven(dataType input)
{
    return (input % 2 == 0);
}

int main()
{
    try
    {
        // get executable folder
        g_exeFolder = getExecutableFolder();

        // Specify an ASCII log file for our application to use. This will be called
        // "log.txt" and will write itself into the executable's folder.
        aie::Log::instance().setLog(g_exeFolder + "\\log.txt");

        // Enable logging for all aie exceptions. When enabled, aie exceptions will
        // also record full details into the log.
        aie::Exception::enableLogging(true);

        // log that the program has started
        aieLOG("Application started");

        // create a Hash Table
        HashTable<unsigned int>table(10);
        table["abomasnow-f"] = 1;
        table["abomasnow-mega"] = 1;
        table["abomasnow"] = 1;
        table["abra"] = 1;
        table["absol-mega"] = 1;
        table["absol"] = 1;
        table["accelgor"] = 1;
        table["aegislash-blade"] = 1;
        table["aegislash-shield"] = 1;
        table["aegislash"] = 1;
        table["aerodactyl-mega"] = 1;
        table["aerodactyl"] = 1;
        table["aggron-mega"] = 1;
        table["aggron"] = 1;
        table["aipom-f"] = 1;
        table["aipom"] = 1;
        table["alakazam-f"] = 1;
        table["alakazam-mega"] = 1;
        table["alakazam"] = 1;
        table["alomomola"] = 1;
        table["altaria-mega"] = 1;
        table["altaria"] = 1;
        table["amaura"] = 1;
        table["ambipom-f"] = 1;
        table["ambipom"] = 1;
        table["amoonguss"] = 1;
        table["ampharos-mega"] = 1;
        table["ampharos"] = 1;
        table["anorith"] = 1;
        table["arbok"] = 1;
        table["arcanine"] = 1;
        table["arceus-bug"] = 1;
        table["arceus-dark"] = 1;
        table["arceus-dragon"] = 1;
        table["arceus-electric"] = 1;
        table["arceus-fairy"] = 1;
        table["arceus-fighting"] = 1;
        table["arceus-fire"] = 1;
        table["arceus-flying"] = 1;
        table["arceus-ghost"] = 1;
        table["arceus-grass"] = 1;
        table["arceus-ground"] = 1;
        table["arceus-ice"] = 1;
        table["arceus-normal"] = 1;
        table["arceus-poison"] = 1;
        table["arceus-psychic"] = 1;
        table["arceus-rock"] = 1;
        table["arceus-steel"] = 1;
        table["arceus-water"] = 1;
        table["arceus"] = 1;
        table["archen"] = 1;
        table["archeops"] = 1;
        table["ariados"] = 1;
        table["armaldo"] = 1;
        table["aromatisse"] = 1;
        table["aron"] = 1;
        table["articuno"] = 1;
        table["audino-mega"] = 1;
        table["audino"] = 1;
        table["aurorus"] = 1;
        table["aurumoth"] = 1;
        table["avalugg"] = 1;
        table["axew"] = 1;
        table["azelf"] = 1;
        table["azumarill"] = 1;
        table["azurill"] = 1;
        table["bagon"] = 1;
        table["baltoy"] = 1;
        table["banette-mega"] = 1;
        table["banette"] = 1;
        table["barbaracle"] = 1;
        table["barboach"] = 1;
        table["basculin-bluestriped"] = 1;
        table["basculin"] = 1;
        table["bastiodon"] = 1;
        table["bayleef"] = 1;
        table["beartic"] = 1;
        table["beautifly-f"] = 1;
        table["beautifly"] = 1;
        table["beedrill-mega"] = 1;
        table["beedrill"] = 1;
        table["beheeyem"] = 1;
        table["beldum"] = 1;
        table["bellossom"] = 1;
        table["bellsprout"] = 1;
        table["bergmite"] = 1;
        table["bibarel-f"] = 1;
        table["bibarel"] = 1;
        table["bidoof-f"] = 1;
        table["bidoof"] = 1;
        table["binacle"] = 1;
        table["bisharp"] = 1;
        table["blastoise-mega"] = 1;
        table["blastoise"] = 1;
        table["blaziken-f"] = 1;
        table["blaziken-mega"] = 1;
        table["blaziken"] = 1;
        table["blissey"] = 1;
        table["blitzle"] = 1;
        table["boldore"] = 1;
        table["bonsly"] = 1;
        table["bouffalant"] = 1;
        table["braixen"] = 1;
        table["braviary"] = 1;
        table["breloom"] = 1;
        table["bronzong"] = 1;
        table["bronzor"] = 1;
        table["budew"] = 1;
        table["buizel-f"] = 1;
        table["buizel"] = 1;
        table["bulbasaur"] = 1;
        table["buneary"] = 1;
        table["bunnelby"] = 1;
        table["burmy-plant"] = 1;
        table["burmy-sandy"] = 1;
        table["burmy-trash"] = 1;
        table["burmy"] = 1;
        table["butterfree-f"] = 1;
        table["butterfree"] = 1;
        table["cacnea"] = 1;
        table["cacturne-f"] = 1;
        table["cacturne"] = 1;
        table["camerupt-f"] = 1;
        table["camerupt-mega"] = 1;
        table["camerupt"] = 1;
        table["carbink"] = 1;
        table["carnivine"] = 1;
        table["carracosta"] = 1;
        table["carvanha"] = 1;
        table["cascoon"] = 1;
        table["castform-rainy"] = 1;
        table["castform-snowy"] = 1;
        table["castform-sunny"] = 1;
        table["castform"] = 1;
        table["caterpie"] = 1;
        table["celebi"] = 1;
        table["chandelure"] = 1;
        table["chansey"] = 1;
        table["charizard-megax"] = 1;
        table["charizard-megay"] = 1;
        table["charizard"] = 1;
        table["charmander"] = 1;
        table["charmeleon"] = 1;
        table["chatot"] = 1;
        table["cherrim-overcast"] = 1;
        table["cherrim-sunshine"] = 1;
        table["cherrim"] = 1;
        table["cherubi"] = 1;
        table["chesnaught"] = 1;
        table["chespin"] = 1;
        table["chikorita"] = 1;
        table["chimchar"] = 1;
        table["chimecho"] = 1;
        table["chinchou"] = 1;
        table["chingling"] = 1;
        table["cinccino"] = 1;
        table["clamperl"] = 1;
        table["clauncher"] = 1;
        table["clawitzer"] = 1;
        table["claydol"] = 1;
        table["clefable"] = 1;
        table["clefairy"] = 1;
        table["cleffa"] = 1;
        table["cloyster"] = 1;
        table["cobalion"] = 1;
        table["cofagrigus"] = 1;
        table["combee-f"] = 1;
        table["combee"] = 1;
        table["combusken-f"] = 1;
        table["combusken"] = 1;
        table["conkeldurr"] = 1;
        table["corphish"] = 1;
        table["corsola"] = 1;
        table["cottonee"] = 1;
        table["cradily"] = 1;
        table["cranidos"] = 1;
        table["crawdaunt"] = 1;
        table["cresselia"] = 1;
        table["croagunk-f"] = 1;
        table["croagunk"] = 1;
        table["crobat"] = 1;
        table["croconaw"] = 1;
        table["crustle"] = 1;
        table["cryogonal"] = 1;
        table["cubchoo"] = 1;
        table["cubone"] = 1;
        table["cyndaquil"] = 1;
        table["darkrai"] = 1;
        table["darmanitan-standard"] = 1;
        table["darmanitan-zen"] = 1;
        table["darmanitan"] = 1;
        table["darumaka"] = 1;
        table["dedenne"] = 1;
        table["deerling-autumn"] = 1;
        table["deerling-spring"] = 1;
        table["deerling-summer"] = 1;
        table["deerling-winter"] = 1;
        table["deerling"] = 1;
        table["deino"] = 1;
        table["delcatty"] = 1;
        table["delibird"] = 1;
        table["delphox"] = 1;
        table["deoxys-attack"] = 1;
        table["deoxys-defense"] = 1;
        table["deoxys-normal"] = 1;
        table["deoxys-speed"] = 1;
        table["deoxys"] = 1;
        table["dewgong"] = 1;
        table["dewott"] = 1;
        table["dialga"] = 1;
        table["diancie-mega"] = 1;
        table["diancie"] = 1;
        table["diggersby"] = 1;
        table["diglett"] = 1;
        table["ditto"] = 1;
        table["dodrio-f"] = 1;
        table["dodrio"] = 1;
        table["doduo-f"] = 1;
        table["doduo"] = 1;
        table["donphan-f"] = 1;
        table["donphan"] = 1;
        table["doublade"] = 1;
        table["dragalge"] = 1;
        table["dragonair"] = 1;
        table["dragonite"] = 1;
        table["drapion"] = 1;
        table["dratini"] = 1;
        table["drifblim"] = 1;
        table["drifloon"] = 1;
        table["drilbur"] = 1;
        table["drowzee"] = 1;
        table["druddigon"] = 1;
        table["ducklett"] = 1;
        table["dugtrio"] = 1;
        table["dunsparce"] = 1;
        table["duosion"] = 1;
        table["durant"] = 1;
        table["dusclops"] = 1;
        table["dusknoir"] = 1;
        table["duskull"] = 1;
        table["dustox-f"] = 1;
        table["dustox"] = 1;
        table["dwebble"] = 1;
        table["eelektrik"] = 1;
        table["eelektross"] = 1;
        table["eevee"] = 1;
        table["ekans"] = 1;
        table["electabuzz"] = 1;
        table["electivire"] = 1;
        table["electrike"] = 1;
        table["electrode"] = 1;
        table["elekid"] = 1;
        table["elgyem"] = 1;
        table["emboar"] = 1;
        table["emolga"] = 1;
        table["empoleon"] = 1;
        table["entei"] = 1;
        table["escavalier"] = 1;
        table["espeon"] = 1;
        table["espurr"] = 1;
        table["excadrill"] = 1;
        table["exeggcute"] = 1;
        table["exeggutor"] = 1;
        table["exploud"] = 1;
        table["farfetchd"] = 1;
        table["fearow"] = 1;
        table["feebas"] = 1;
        table["fennekin"] = 1;
        table["feraligatr"] = 1;
        table["ferroseed"] = 1;
        table["ferrothorn"] = 1;
        table["finneon-f"] = 1;
        table["finneon"] = 1;
        table["flaaffy"] = 1;
        table["flabebe-blue"] = 1;
        table["flabebe-orange"] = 1;
        table["flabebe-red"] = 1;
        table["flabebe-white"] = 1;
        table["flabebe-yellow"] = 1;
        table["flabebe"] = 1;
        table["flareon"] = 1;
        table["fletchinder"] = 1;
        table["fletchling"] = 1;
        table["floatzel-f"] = 1;
        table["floatzel"] = 1;
        table["floette-az"] = 1;
        table["floette-blue"] = 1;
        table["floette-eternal"] = 1;
        table["floette-orange"] = 1;
        table["floette-red"] = 1;
        table["floette-white"] = 1;
        table["floette-yellow"] = 1;
        table["floette"] = 1;
        table["florges-blue"] = 1;
        table["florges-orange"] = 1;
        table["florges-red"] = 1;
        table["florges-white"] = 1;
        table["florges-yellow"] = 1;
        table["florges"] = 1;
        table["flygon"] = 1;
        table["foongus"] = 1;
        table["forretress"] = 1;
        table["fraxure"] = 1;
        table["frillish-f"] = 1;
        table["frillish"] = 1;
        table["froakie"] = 1;
        table["frogadier"] = 1;
        table["froslass"] = 1;
        table["furfrou-dandy"] = 1;
        table["furfrou-debutante"] = 1;
        table["furfrou-diamond"] = 1;
        table["furfrou-heart"] = 1;
        table["furfrou-kabuki"] = 1;
        table["furfrou-la-reine"] = 1;
        table["furfrou-matron"] = 1;
        table["furfrou-natural"] = 1;
        table["furfrou-pharaoh"] = 1;
        table["furfrou-star"] = 1;
        table["furfrou"] = 1;
        table["furret"] = 1;
        table["gabite-f"] = 1;
        table["gabite"] = 1;
        table["gallade-mega"] = 1;
        table["gallade"] = 1;
        table["galvantula"] = 1;
        table["garbodor"] = 1;
        table["garchomp-f"] = 1;
        table["garchomp-mega"] = 1;
        table["garchomp"] = 1;
        table["gardevoir-mega"] = 1;
        table["gardevoir"] = 1;
        table["gastly"] = 1;
        table["gastrodon-east"] = 1;
        table["gastrodon-west"] = 1;
        table["gastrodon"] = 1;
        table["genesect-burn"] = 1;
        table["genesect-chill"] = 1;
        table["genesect-douse"] = 1;
        table["genesect-shock"] = 1;
        table["genesect"] = 1;
        table["gengar-mega"] = 1;
        table["gengar"] = 1;
        table["geodude"] = 1;
        table["gible-f"] = 1;
        table["gible"] = 1;
        table["gigalith"] = 1;
        table["girafarig-f"] = 1;
        table["girafarig"] = 1;
        table["giratina-altered"] = 1;
        table["giratina-origin"] = 1;
        table["giratina"] = 1;
        table["glaceon"] = 1;
        table["glalie-mega"] = 1;
        table["glalie"] = 1;
        table["glameow"] = 1;
        table["gligar-f"] = 1;
        table["gligar"] = 1;
        table["gliscor"] = 1;
        table["gloom-f"] = 1;
        table["gloom"] = 1;
        table["gogoat"] = 1;
        table["golbat-f"] = 1;
        table["golbat"] = 1;
        table["goldeen-f"] = 1;
        table["goldeen"] = 1;
        table["golduck"] = 1;
        table["golem"] = 1;
        table["golett"] = 1;
        table["golurk"] = 1;
        table["goodra"] = 1;
        table["goomy"] = 1;
        table["gorebyss"] = 1;
        table["gothita"] = 1;
        table["gothitelle"] = 1;
        table["gothorita"] = 1;
        table["gourgeist-average"] = 1;
        table["gourgeist-large"] = 1;
        table["gourgeist-small"] = 1;
        table["gourgeist-super"] = 1;
        table["gourgeist"] = 1;
        table["granbull"] = 1;
        table["graveler"] = 1;
        table["greninja"] = 1;
        table["grimer"] = 1;
        table["grotle"] = 1;
        table["groudon-primal"] = 1;
        table["groudon"] = 1;
        table["grovyle"] = 1;
        table["growlithe"] = 1;
        table["grumpig"] = 1;
        table["gulpin-f"] = 1;
        table["gulpin"] = 1;
        table["gurdurr"] = 1;
        table["gyarados-f"] = 1;
        table["gyarados-mega"] = 1;
        table["gyarados"] = 1;
        table["happiny"] = 1;
        table["hariyama"] = 1;
        table["haunter"] = 1;
        table["hawlucha"] = 1;
        table["haxorus"] = 1;
        table["heatmor"] = 1;
        table["heatran"] = 1;
        table["heliolisk"] = 1;
        table["helioptile"] = 1;
        table["heracross-f"] = 1;
        table["heracross-mega"] = 1;
        table["heracross"] = 1;
        table["herdier"] = 1;
        table["hippopotas-f"] = 1;
        table["hippopotas"] = 1;
        table["hippowdon-f"] = 1;
        table["hippowdon"] = 1;
        table["hitmonchan"] = 1;
        table["hitmonlee"] = 1;
        table["hitmontop"] = 1;
        table["honchkrow"] = 1;
        table["honedge"] = 1;
        table["hooh"] = 1;
        table["hoopa-confined"] = 1;
        table["hoopa-unbound"] = 1;
        table["hoopa"] = 1;
        table["hoothoot"] = 1;
        table["hoppip"] = 1;
        table["horsea"] = 1;
        table["houndoom-f"] = 1;
        table["houndoom-mega"] = 1;
        table["houndoom"] = 1;
        table["houndour"] = 1;
        table["huntail"] = 1;
        table["hydreigon"] = 1;
        table["hypno-f"] = 1;
        table["hypno"] = 1;
        table["igglybuff"] = 1;
        table["illumise"] = 1;
        table["infernape"] = 1;
        table["inkay"] = 1;
        table["ivysaur"] = 1;
        table["jellicent-f"] = 1;
        table["jellicent"] = 1;
        table["jigglypuff"] = 1;
        table["jirachi"] = 1;
        table["jolteon"] = 1;
        table["joltik"] = 1;
        table["jumpluff"] = 1;
        table["jynx"] = 1;
        table["kabuto"] = 1;
        table["kabutops"] = 1;
        table["kadabra-f"] = 1;
        table["kadabra"] = 1;
        table["kakuna"] = 1;
        table["kangaskhan-mega"] = 1;
        table["kangaskhan"] = 1;
        table["karrablast"] = 1;
        table["kecleon"] = 1;
        table["keldeo-ordinary"] = 1;
        table["keldeo-resolute"] = 1;
        table["keldeo"] = 1;
        table["kingdra"] = 1;
        table["kingler"] = 1;
        table["kirlia"] = 1;
        table["klang"] = 1;
        table["klefki"] = 1;
        table["klink"] = 1;
        table["klinklang"] = 1;
        table["koffing"] = 1;
        table["krabby"] = 1;
        table["kricketot-f"] = 1;
        table["kricketot"] = 1;
        table["kricketune-f"] = 1;
        table["kricketune"] = 1;
        table["krilowatt"] = 1;
        table["krokorok"] = 1;
        table["krookodile"] = 1;
        table["kyogre-primal"] = 1;
        table["kyogre"] = 1;
        table["kyurem-black"] = 1;
        table["kyurem-white"] = 1;
        table["kyurem"] = 1;
        table["lairon"] = 1;
        table["lampent"] = 1;
        table["landorus-incarnate"] = 1;
        table["landorus-therian"] = 1;
        table["landorus"] = 1;
        table["lanturn"] = 1;
        table["lapras"] = 1;
        table["larvesta"] = 1;
        table["larvitar"] = 1;
        table["latias-mega"] = 1;
        table["latias"] = 1;
        table["latios-mega"] = 1;
        table["latios"] = 1;
        table["leafeon"] = 1;
        table["leavanny"] = 1;
        table["ledian-f"] = 1;
        table["ledian"] = 1;
        table["ledyba-f"] = 1;
        table["ledyba"] = 1;
        table["lickilicky"] = 1;
        table["lickitung"] = 1;
        table["liepard"] = 1;
        table["lileep"] = 1;
        table["lilligant"] = 1;
        table["lillipup"] = 1;
        table["linoone"] = 1;
        table["litleo"] = 1;
        table["litwick"] = 1;
        table["lombre"] = 1;
        table["lopunny-mega"] = 1;
        table["lopunny"] = 1;
        table["lotad"] = 1;
        table["loudred"] = 1;
        table["lucario-mega"] = 1;
        table["lucario"] = 1;
        table["ludicolo-f"] = 1;
        table["ludicolo"] = 1;
        table["lugia"] = 1;
        table["lumineon-f"] = 1;
        table["lumineon"] = 1;
        table["lunatone"] = 1;
        table["luvdisc"] = 1;
        table["luxio-f"] = 1;
        table["luxio"] = 1;
        table["luxray-f"] = 1;
        table["luxray"] = 1;
        table["machamp"] = 1;
        table["machoke"] = 1;
        table["machop"] = 1;
        table["magby"] = 1;
        table["magcargo"] = 1;
        table["magikarp-f"] = 1;
        table["magikarp"] = 1;
        table["magmar"] = 1;
        table["magmortar"] = 1;
        table["magnemite"] = 1;
        table["magneton"] = 1;
        table["magnezone"] = 1;
        table["makuhita"] = 1;
        table["malamar"] = 1;
        table["mamoswine-f"] = 1;
        table["mamoswine"] = 1;
        table["manaphy"] = 1;
        table["mandibuzz"] = 1;
        table["manectric-mega"] = 1;
        table["manectric"] = 1;
        table["mankey"] = 1;
        table["mantine"] = 1;
        table["mantyke"] = 1;
        table["maractus"] = 1;
        table["mareep"] = 1;
        table["marill"] = 1;
        table["marowak"] = 1;
        table["marshtomp"] = 1;
        table["masquerain"] = 1;
        table["mawile-mega"] = 1;
        table["mawile"] = 1;
        table["medicham-f"] = 1;
        table["medicham-mega"] = 1;
        table["medicham"] = 1;
        table["meditite-f"] = 1;
        table["meditite"] = 1;
        table["meganium-f"] = 1;
        table["meganium"] = 1;
        table["meloetta-aria"] = 1;
        table["meloetta-pirouette"] = 1;
        table["meloetta"] = 1;
        table["meowstic-f"] = 1;
        table["meowstic-female"] = 1;
        table["meowstic-male"] = 1;
        table["meowstic"] = 1;
        table["meowth"] = 1;
        table["mesprit"] = 1;
        table["metagross-mega"] = 1;
        table["metagross"] = 1;
        table["metang"] = 1;
        table["metapod"] = 1;
        table["mew"] = 1;
        table["mewtwo-megax"] = 1;
        table["mewtwo-megay"] = 1;
        table["mewtwo"] = 1;
        table["mienfoo"] = 1;
        table["mienshao"] = 1;
        table["mightyena"] = 1;
        table["milotic-f"] = 1;
        table["milotic"] = 1;
        table["miltank"] = 1;
        table["mime-jr"] = 1;
        table["mimejr"] = 1;
        table["minccino"] = 1;
        table["minun"] = 1;
        table["misdreavus"] = 1;
        table["mismagius"] = 1;
        table["moltres"] = 1;
        table["monferno"] = 1;
        table["mothim"] = 1;
        table["mr-mime"] = 1;
        table["mrmime"] = 1;
        table["mudkip"] = 1;
        table["muk"] = 1;
        table["munchlax"] = 1;
        table["munna"] = 1;
        table["murkrow-f"] = 1;
        table["murkrow"] = 1;
        table["musharna"] = 1;
        table["natu"] = 1;
        table["naviathan"] = 1;
        table["nidoking"] = 1;
        table["nidoqueen"] = 1;
        table["nidoran-f"] = 1;
        table["nidoran-m"] = 1;
        table["nidoran"] = 1;
        table["nidoranf"] = 1;
        table["nidoranm"] = 1;
        table["nidorina"] = 1;
        table["nidorino"] = 1;
        table["nincada"] = 1;
        table["ninetales"] = 1;
        table["ninjask"] = 1;
        table["noctowl"] = 1;
        table["noibat"] = 1;
        table["noivern"] = 1;
        table["nosepass"] = 1;
        table["numel-f"] = 1;
        table["numel"] = 1;
        table["nuzleaf-f"] = 1;
        table["nuzleaf"] = 1;
        table["octillery-f"] = 1;
        table["octillery"] = 1;
        table["oddish"] = 1;
        table["omanyte"] = 1;
        table["omastar"] = 1;
        table["onix"] = 1;
        table["oshawott"] = 1;
        table["pachirisu-f"] = 1;
        table["pachirisu"] = 1;
        table["palkia"] = 1;
        table["palpitoad"] = 1;
        table["pancham"] = 1;
        table["pangoro"] = 1;
        table["panpour"] = 1;
        table["pansage"] = 1;
        table["pansear"] = 1;
        table["paras"] = 1;
        table["parasect"] = 1;
        table["patrat"] = 1;
        table["pawniard"] = 1;
        table["pelipper"] = 1;
        table["persian"] = 1;
        table["petilil"] = 1;
        table["phanpy"] = 1;
        table["phantump"] = 1;
        table["phione"] = 1;
        table["pichu"] = 1;
        table["pidgeot-mega"] = 1;
        table["pidgeot"] = 1;
        table["pidgeotto"] = 1;
        table["pidgey"] = 1;
        table["pidove"] = 1;
        table["pignite"] = 1;
        table["pikachu-cosplay"] = 1;
        table["pikachu-f"] = 1;
        table["pikachu"] = 1;
        table["piloswine-f"] = 1;
        table["piloswine"] = 1;
        table["pineco"] = 1;
        table["pinsir-mega"] = 1;
        table["pinsir"] = 1;
        table["piplup"] = 1;
        table["plasmanta"] = 1;
        table["plusle"] = 1;
        table["politoed-f"] = 1;
        table["politoed"] = 1;
        table["poliwag"] = 1;
        table["poliwhirl"] = 1;
        table["poliwrath"] = 1;
        table["ponyta"] = 1;
        table["poochyena"] = 1;
        table["porygon-z"] = 1;
        table["porygon"] = 1;
        table["porygon2"] = 1;
        table["porygonz"] = 1;
        table["primeape"] = 1;
        table["prinplup"] = 1;
        table["probopass"] = 1;
        table["psyduck"] = 1;
        table["pumpkaboo-average"] = 1;
        table["pumpkaboo-large"] = 1;
        table["pumpkaboo-small"] = 1;
        table["pumpkaboo-super"] = 1;
        table["pumpkaboo"] = 1;
        table["pupitar"] = 1;
        table["purrloin"] = 1;
        table["purugly"] = 1;
        table["pyroar-f"] = 1;
        table["pyroar"] = 1;
        table["quagsire-f"] = 1;
        table["quagsire"] = 1;
        table["quilava"] = 1;
        table["quilladin"] = 1;
        table["qwilfish"] = 1;
        table["raichu-f"] = 1;
        table["raichu"] = 1;
        table["raikou"] = 1;
        table["ralts"] = 1;
        table["rampardos"] = 1;
        table["rapidash"] = 1;
        table["raticate-f"] = 1;
        table["raticate"] = 1;
        table["rattata-f"] = 1;
        table["rattata"] = 1;
        table["rayquaza-mega"] = 1;
        table["rayquaza"] = 1;
        table["regice"] = 1;
        table["regigigas"] = 1;
        table["regirock"] = 1;
        table["registeel"] = 1;
        table["relicanth-f"] = 1;
        table["relicanth"] = 1;
        table["remoraid"] = 1;
        table["reshiram"] = 1;
        table["reuniclus"] = 1;
        table["rhydon-f"] = 1;
        table["rhydon"] = 1;
        table["rhyhorn-f"] = 1;
        table["rhyhorn"] = 1;
        table["rhyperior-f"] = 1;
        table["rhyperior"] = 1;
        table["riolu"] = 1;
        table["roggenrola"] = 1;
        table["roselia-f"] = 1;
        table["roselia"] = 1;
        table["roserade-f"] = 1;
        table["roserade"] = 1;
        table["rotom-f"] = 1;
        table["rotom-fan"] = 1;
        table["rotom-frost"] = 1;
        table["rotom-h"] = 1;
        table["rotom-heat"] = 1;
        table["rotom-m"] = 1;
        table["rotom-mow"] = 1;
        table["rotom-s"] = 1;
        table["rotom-w"] = 1;
        table["rotom-wash"] = 1;
        table["rotom"] = 1;
        table["rufflet"] = 1;
        table["sableye-mega"] = 1;
        table["sableye"] = 1;
        table["salamence-mega"] = 1;
        table["salamence"] = 1;
        table["samurott"] = 1;
        table["sandile"] = 1;
        table["sandshrew"] = 1;
        table["sandslash"] = 1;
        table["sawk"] = 1;
        table["sawsbuck-autumn"] = 1;
        table["sawsbuck-spring"] = 1;
        table["sawsbuck-summer"] = 1;
        table["sawsbuck-winter"] = 1;
        table["sawsbuck"] = 1;
        table["scatterbug"] = 1;
        table["sceptile-mega"] = 1;
        table["sceptile"] = 1;
        table["scizor-f"] = 1;
        table["scizor-mega"] = 1;
        table["scizor"] = 1;
        table["scolipede"] = 1;
        table["scrafty"] = 1;
        table["scraggy"] = 1;
        table["scyther-f"] = 1;
        table["scyther"] = 1;
        table["seadra"] = 1;
        table["seaking-f"] = 1;
        table["seaking"] = 1;
        table["sealeo"] = 1;
        table["seedot"] = 1;
        table["seel"] = 1;
        table["seismitoad"] = 1;
        table["sentret"] = 1;
        table["serperior"] = 1;
        table["servine"] = 1;
        table["seviper"] = 1;
        table["sewaddle"] = 1;
        table["sharpedo-mega"] = 1;
        table["sharpedo"] = 1;
        table["shaymin-land"] = 1;
        table["shaymin-sky"] = 1;
        table["shaymin"] = 1;
        table["shedinja"] = 1;
        table["shelgon"] = 1;
        table["shellder"] = 1;
        table["shellos-east"] = 1;
        table["shellos-west"] = 1;
        table["shellos"] = 1;
        table["shelmet"] = 1;
        table["shieldon"] = 1;
        table["shiftry-f"] = 1;
        table["shiftry"] = 1;
        table["shinx-f"] = 1;
        table["shinx"] = 1;
        table["shroomish"] = 1;
        table["shuckle"] = 1;
        table["shuppet"] = 1;
        table["sigilyph"] = 1;
        table["silcoon"] = 1;
        table["simipour"] = 1;
        table["simisage"] = 1;
        table["simisear"] = 1;
        table["skarmory"] = 1;
        table["skiddo"] = 1;
        table["skiploom"] = 1;
        table["skitty"] = 1;
        table["skorupi"] = 1;
        table["skrelp"] = 1;
        table["skuntank"] = 1;
        table["slaking"] = 1;
        table["slakoth"] = 1;
        table["sliggoo"] = 1;
        table["slowbro-mega"] = 1;
        table["slowbro"] = 1;
        table["slowking"] = 1;
        table["slowpoke"] = 1;
        table["slugma"] = 1;
        table["slurpuff"] = 1;
        table["smeargle"] = 1;
        table["smoochum"] = 1;
        table["sneasel-f"] = 1;
        table["sneasel"] = 1;
        table["snivy"] = 1;
        table["snorlax"] = 1;
        table["snorunt"] = 1;
        table["snover-f"] = 1;
        table["snover"] = 1;
        table["snubbull"] = 1;
        table["solosis"] = 1;
        table["solrock"] = 1;
        table["spearow"] = 1;
        table["spewpa"] = 1;
        table["spheal"] = 1;
        table["spinarak"] = 1;
        table["spinda"] = 1;
        table["spiritomb"] = 1;
        table["spoink"] = 1;
        table["spritzee"] = 1;
        table["squirtle"] = 1;
        table["stantler"] = 1;
        table["staraptor-f"] = 1;
        table["staraptor"] = 1;
        table["staravia-f"] = 1;
        table["staravia"] = 1;
        table["starly-f"] = 1;
        table["starly"] = 1;
        table["starmie"] = 1;
        table["staryu"] = 1;
        table["steelix-f"] = 1;
        table["steelix-mega"] = 1;
        table["steelix"] = 1;
        table["stoutland"] = 1;
        table["stratagem"] = 1;
        table["stunfisk"] = 1;
        table["stunky"] = 1;
        table["substitute"] = 1;
        table["sudowoodo-f"] = 1;
        table["sudowoodo"] = 1;
        table["suicune"] = 1;
        table["sunflora"] = 1;
        table["sunkern"] = 1;
        table["surskit"] = 1;
        table["swablu"] = 1;
        table["swadloon"] = 1;
        table["swalot-f"] = 1;
        table["swalot"] = 1;
        table["swampert-mega"] = 1;
        table["swampert"] = 1;
        table["swanna"] = 1;
        table["swellow"] = 1;
        table["swinub"] = 1;
        table["swirlix"] = 1;
        table["swoobat"] = 1;
        table["sylveon"] = 1;
        table["taillow"] = 1;
        table["talonflame"] = 1;
        table["tangela"] = 1;
        table["tangrowth-f"] = 1;
        table["tangrowth"] = 1;
        table["tauros"] = 1;
        table["teddiursa"] = 1;
        table["tentacool"] = 1;
        table["tentacruel"] = 1;
        table["tepig"] = 1;
        table["terrakion"] = 1;
        table["throh"] = 1;
        table["thundurus-incarnate"] = 1;
        table["thundurus-therian"] = 1;
        table["thundurus"] = 1;
        table["timburr"] = 1;
        table["tirtouga"] = 1;
        table["togekiss"] = 1;
        table["togepi"] = 1;
        table["togetic"] = 1;
        table["torchic-f"] = 1;
        table["torchic"] = 1;
        table["torkoal"] = 1;
        table["tornadus-incarnate"] = 1;
        table["tornadus-therian"] = 1;
        table["tornadus"] = 1;
        table["torterra"] = 1;
        table["totodile"] = 1;
        table["toxicroak-f"] = 1;
        table["toxicroak"] = 1;
        table["tranquill"] = 1;
        table["trapinch"] = 1;
        table["treecko"] = 1;
        table["trevenant"] = 1;
        table["tropius"] = 1;
        table["trubbish"] = 1;
        table["turtwig"] = 1;
        table["tympole"] = 1;
        table["tynamo"] = 1;
        table["typhlosion"] = 1;
        table["tyranitar-mega"] = 1;
        table["tyranitar"] = 1;
        table["tyrantrum"] = 1;
        table["tyrogue"] = 1;
        table["tyrunt"] = 1;
        table["umbreon"] = 1;
        table["unfezant-f"] = 1;
        table["unfezant"] = 1;
        table["unown-a"] = 1;
        table["unown-b"] = 1;
        table["unown-c"] = 1;
        table["unown-d"] = 1;
        table["unown-e"] = 1;
        table["unown-exclamation"] = 1;
        table["unown-f"] = 1;
        table["unown-g"] = 1;
        table["unown-h"] = 1;
        table["unown-i"] = 1;
        table["unown-j"] = 1;
        table["unown-k"] = 1;
        table["unown-l"] = 1;
        table["unown-m"] = 1;
        table["unown-n"] = 1;
        table["unown-o"] = 1;
        table["unown-p"] = 1;
        table["unown-q"] = 1;
        table["unown-question"] = 1;
        table["unown-r"] = 1;
        table["unown-s"] = 1;
        table["unown-t"] = 1;
        table["unown-u"] = 1;
        table["unown-v"] = 1;
        table["unown-w"] = 1;
        table["unown-x"] = 1;
        table["unown-y"] = 1;
        table["unown-z"] = 1;
        table["unown"] = 1;
        table["ursaring-f"] = 1;
        table["ursaring"] = 1;
        table["uxie"] = 1;
        table["vanillish"] = 1;
        table["vanillite"] = 1;
        table["vanilluxe"] = 1;
        table["vaporeon"] = 1;
        table["venipede"] = 1;
        table["venomoth"] = 1;
        table["venonat"] = 1;
        table["venusaur-f"] = 1;
        table["venusaur-mega"] = 1;
        table["venusaur"] = 1;
        table["vespiquen"] = 1;
        table["vibrava"] = 1;
        table["victini"] = 1;
        table["victreebel"] = 1;
        table["vigoroth"] = 1;
        table["vileplume-f"] = 1;
        table["vileplume"] = 1;
        table["virizion"] = 1;
        table["vivillon-archipelago"] = 1;
        table["vivillon-continental"] = 1;
        table["vivillon-elegant"] = 1;
        table["vivillon-fancy"] = 1;
        table["vivillon-garden"] = 1;
        table["vivillon-highplains"] = 1;
        table["vivillon-icysnow"] = 1;
        table["vivillon-jungle"] = 1;
        table["vivillon-marine"] = 1;
        table["vivillon-meadow"] = 1;
        table["vivillon-modern"] = 1;
        table["vivillon-monsoon"] = 1;
        table["vivillon-ocean"] = 1;
        table["vivillon-pokeball"] = 1;
        table["vivillon-polar"] = 1;
        table["vivillon-river"] = 1;
        table["vivillon-sandstorm"] = 1;
        table["vivillon-savanna"] = 1;
        table["vivillon-sun"] = 1;
        table["vivillon-tundra"] = 1;
        table["vivillon"] = 1;
        table["volbeat"] = 1;
        table["volcanion"] = 1;
        table["volcarona"] = 1;
        table["voltorb"] = 1;
        table["vullaby"] = 1;
        table["vulpix"] = 1;
        table["wailmer"] = 1;
        table["wailord"] = 1;
        table["walrein"] = 1;
        table["wartortle"] = 1;
        table["watchog"] = 1;
        table["weavile-f"] = 1;
        table["weavile"] = 1;
        table["weedle"] = 1;
        table["weepinbell"] = 1;
        table["weezing"] = 1;
        table["whimsicott"] = 1;
        table["whirlipede"] = 1;
        table["whiscash"] = 1;
        table["whismur"] = 1;
        table["wigglytuff"] = 1;
        table["wingull"] = 1;
        table["wobbuffet-f"] = 1;
        table["wobbuffet"] = 1;
        table["woobat"] = 1;
        table["wooper-f"] = 1;
        table["wooper"] = 1;
        table["wormadam-plant"] = 1;
        table["wormadam-sandy"] = 1;
        table["wormadam-trash"] = 1;
        table["wormadam"] = 1;
        table["wurmple"] = 1;
        table["wynaut"] = 1;
        table["xatu-f"] = 1;
        table["xatu"] = 1;
        table["xerneas-active"] = 1;
        table["xerneas-neutral"] = 1;
        table["xerneas"] = 1;
        table["yamask"] = 1;
        table["yanma"] = 1;
        table["yanmega"] = 1;
        table["yveltal"] = 1;
        table["zangoose"] = 1;
        table["zapdos"] = 1;
        table["zebstrika"] = 1;
        table["zekrom"] = 1;
        table["zigzagoon"] = 1;
        table["zoroark"] = 1;
        table["zorua"] = 1;
        table["zubat-f"] = 1;
        table["zubat"] = 1;
        table["zweilous"] = 1;
        table["zygarde"] = 1;

        std::cout << "table[\"charmander\"] = " << table["charmander"] << std::endl;
        std::cout << "table.getLoadFactor() = " << table.getLoadFactor() << std::endl;


        //treeNode<int> myTree(10);
        //myTree.insert(5);
        //myTree.insert(7);
        //myTree.insert(15);
        //myTree.insert(12);
        //myTree.insert(17);
        //myTree.insert(14);

        //std::cout << "found " << myTree.findNode(15)->getValue() << std::endl;

        //myTree.getRoot()->getRight()->remove();

        ////std::cout << std::hex << HashFunction::default<char*>((char*)"Andrew") << std::endl << std::dec;

        //// create List of int
        //List<int> myList;

        //// push some numbers onto the back
        //myList.pushBack(5);
        //myList.pushBack(6);
        //myList.pushBack(7);
        //myList.pushBack(8);

        //// push some more numbers onto the front
        //myList.pushFront(4);
        //myList.pushFront(3);
        //myList.pushFront(2);
        //myList.pushFront(1);

        //// create function pointer
        //bool(*predicate)(int);
        //predicate = isEven;

        //// remove values from list that meet the predicate
        //myList.remove(predicate);

        //// remove any 7s
        //myList.remove(7);

        //// print out each value using an iterator
        //for (auto iter = myList.begin(); iter != myList.end(); iter++)
        //{
        //    std::cout << iter.getNode()->value << " ";
        //}
        //std::cout << std::endl;

        //// print out the number of elements
        //std::cout << "There are " << myList.count() << " elements." << std::endl;

        //// clear the list
        //myList.clear();

        //aieASSERT(myList.empty());
    }
    catch (const std::exception& e)
    {
        std::cout << "\n\n\n" << e.what() << "\n\n\n";
    }

    catch (const aie::Exception& e)
    {
        std::cout << "\n\n\n" << e.reason() << "\n\n\n";
    }

    system("pause");
    return 0;
}